[package]
name = "shrinkray"
version = "1.1.1"
edition = "2024"
rust-version = "1.90.0"
description = "Lightning-fast image resizing & optimisation for the web"
homepage = "https://shrinkray.photo"
authors = ["Don Schonknecht <don@tpyo.net>"]
repository = "https://github.com/tpyo/shrinkray"
readme = "README.md"
license = "MIT"
build = "build.rs"
exclude = ["tests/*", ".vscode", ".github"]
categories = ["multimedia::images", "multimedia::encoding", "graphics"]
keywords = ["libvips", "vips", "image", "resize", "thumbnail"]

[lib]
name = "shrinkray"
path = "src/lib.rs"

[dependencies]
hex = "0.4.3"
libvips = "2.1.0"
once_cell = "1.21.4"
rexif = "0.7.5"
ring = "0.17.14"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strum = { version = "0.28.0", features = ["derive"] }
tracing = "0.1.44"

[dev-dependencies]
axum = { version = "0.8.9", default-features = false, features = ["query"] }
rstest = "0.26.1"
