FROM rust:1.94.0-alpine3.23 AS build

ARG libaom_version=v3.13.1
ARG libheif_version=v1.21.2
ARG libvips_version=v8.17.3

ENV PKG_CONFIG_PATH="/opt/shrinkray/lib/pkgconfig"
ENV LD_LIBRARY_PATH="/opt/shrinkray/lib:/usr/lib"
ENV SHRINKRAY_LIB_PATH="/opt/shrinkray/lib"
ENV PATH="/opt/shrinkray/bin:$PATH"

# Install build dependencies
RUN apk add --no-cache \
    autoconf \
    automake \
    build-base \
    cmake \
    clang \
    ninja \
    meson \
    git \
    gpg \
    orc-dev \
    libde265-dev \
    freetype-dev \
    fftw-dev \
    lcms2-dev \
    x265-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    librsvg-dev \
    highway-dev \
    libtool \
    openssl-dev \
    glib-dev \
    expat-dev \
    libexif-dev \
    libwebp-dev \
    libwebpmux \
    libwebpdemux \
    openssl \
    texinfo \
    zlib-dev \
    yasm \
    nasm \
    pkgconfig \
    curl \
    ca-certificates

RUN mkdir -p /opt/shrinkray/lib/pkgconfig

# Build libaom
WORKDIR /opt/libaom
RUN git clone --branch ${libaom_version} --depth 1 https://aomedia.googlesource.com/aom .
RUN mkdir -p ../aom_build
WORKDIR /opt/libaom/aom_build
RUN cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/opt/shrinkray" \
    -DBUILD_SHARED_LIBS=off \
    -DENABLE_TOOLS=off \
    -DENABLE_DOCS=off \
    -DENABLE_EXAMPLES=off \
    -DENABLE_TESTS=off \
    -DENABLE_NASM=on \
    -DCMAKE_BUILD_TYPE=Release \
    ../
RUN make -j$(nproc)
RUN make install
RUN cp aom.pc /opt/shrinkray/lib/pkgconfig/
RUN pkg-config aom

# Build libheif
WORKDIR /opt/libheif
RUN git clone --branch ${libheif_version} --depth 1 https://github.com/strukturag/libheif.git .
RUN cmake -DCMAKE_INSTALL_PREFIX=/opt/shrinkray -DCMAKE_BUILD_TYPE=Release -DWITH_EXAMPLES=0 -DWITH_SvtEnc=0 -DWITH_RAV1E=0 .
RUN make -j$(nproc)
RUN make install
RUN cp libheif.pc /opt/shrinkray/lib/pkgconfig/
RUN pkg-config libheif --modversion

# Build libvips
WORKDIR /opt/libvips
RUN git clone --branch ${libvips_version} --depth 1 https://github.com/libvips/libvips.git .
RUN meson setup build-dir --prefix=/opt/shrinkray --buildtype=release --includedir=/opt/shrinkray/include --libdir=/opt/shrinkray/lib
WORKDIR /opt/libvips/build-dir
RUN ninja
RUN ninja install
