FROM ghcr.io/tpyo/shrinkray/base:latest

ENV PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/shrinkray/lib/pkgconfig"
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/shrinkray/lib"
ENV SHRINKRAY_LIB_PATH="/opt/shrinkray/lib"
ENV PATH="$PATH:/opt/shrinkray/bin"

RUN apt-get -y install cargo rustc --no-install-recommends

RUN cargo install --locked watchexec-cli@2.4.3

RUN dpkg -L libjemalloc2 | grep 'libjemalloc.so.2$' > /etc/ld.so.preload

WORKDIR /app
