[package]
name = "shrinkray-server"
version = "1.0.2"
edition = "2024"
publish = false
rust-version = "1.90.0"
authors = ["Don Schonknecht <don@tpyo.net>"]
build = "../lib/build.rs"

[[bin]]
name = "shrinkray"
path = "src/main.rs"

[dependencies]
shrinkray = { path = "../lib" }

async-trait = "0.1.89"
aws-sign-v4 = "0.3.0"
axum = { version = "0.8.8", default-features = false, features = [
    "tokio",
    "http1",
    "query",
    "matched-path",
    "macros",
    "tracing",
] }
axum-extra = "0.12.2"
chrono = "0.4.42"
hex = "0.4.3"
ipnet = { version = "2.11.0", features = ["serde"] }
libvips = "1.7.3"
metrics = { version = "0.24.3", default-features = false }
metrics-exporter-prometheus = { version = "0.18.1", default-features = false }
once_cell = "1.21.3"
opentelemetry = "0.31.0"
opentelemetry-otlp = { version = "0.31.0", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.31.0", features = ["rt-tokio"] }
rayon = "1.11.0"
reqwest = { version = "0.12.28", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rexif = "0.7.5"
ring = "0.17.14"
rstest = "0.26.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", default-features = false, features = ["full"] }
tracing = "0.1.44"
tracing-opentelemetry = "0.32.0"
tracing-subscriber = { version = "0.3.22", features = ["json", "env-filter"] }
url = "2.5.7"

[dev-dependencies]
axum-test = "18.4.1"
mockito = "1.7.1"
regex = "1.12.2"
tracing-test = "0.2.5"
